### ISSUE TITLE
点击 Flutter Inspector 的 select widget mode 报错

### ISSUE THREAD

**Issue by Elikke-007** [fluttercandies/flutter_smart_dialog#101]
### 版本信息
- Flutter版本：3.3.10
- flutter_smart_dialog版本：4.8.0

### 描述bug/需求
从浏览器点击 select widget mode 出现报错，从 Android studio 内部的 Flutter Inspector 点击 select widget mode 也是一样的报错。
报错信息如下：
One or more of the specified entries are already present in another Overlay.
'package:flutter/src/widgets/overlay.dart':
Failed assertion: line 427 pos 7: 'entries.every((OverlayEntry entry) => entry._overlay == null)'

### 问题demo
[smart_dialog_demo.zip](https://github.com/fluttercandies/flutter_smart_dialog/files/10359548/smart_dialog_demo.zip)

**Comment by xdd666t** [comment]
- 这个问题解决了，更新到新版本再试试

```dart
dependencies:
  flutter_smart_dialog: ^4.8.1
```

**Comment by howe-Guo** [comment]
![image](https://user-images.githubusercontent.com/27638399/216935406-9e6652e7-3ce1-4a69-9e26-7fc61f2e4d6c.png)
../../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_smart_dialog-4.8.2+2/lib/src/util/view_utils.dart:21:55: Error: A value of type 'OverlayState?' can't be returned from a function with return type 'OverlayState' because 'OverlayState?' is nullable and 'OverlayState' isn't.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('../../../../flutter/packages/flutter/lib/src/widgets/overlay.dart').
OverlayState overlay(BuildContext context) => Overlay.of(context);

**Comment by xdd666t** [comment]
flutter 3.7版本的改动是不可空了，我晚上把这个还原下吧，感觉对flutter低版本不太友好

**Comment by xdd666t** [comment]
- @howe-Guo 试试新版本
```dart
dependencies:
  flutter_smart_dialog: ^4.8.2+3
```

**Comment by howe-Guo** [comment]
收到，你真棒！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月06日 22:18 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [fluttercandies/flutter_smart_dialog] 点击 Flutter Inspector 的 select widget mode 报错 (Issue #101) |

@howe-Guo 试试新版本
dependencies:

  flutter_smart_dialog:^4.8.2+3

**Comment by CatEatFishs** [comment]
遇到相同的问题，flutter_smart_dialog版本：4.9.7+8 ， flutter版本 3.3.9 
`../../develop/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_smart_dialog-4.9.7+8/lib/src/kit/view_utils.dart:19:55: Error: A value of type 'OverlayState?' can't be returned from a function with return type 'OverlayState' because 'OverlayState?' is nullable and 'OverlayState' isn't.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('../../develop/flutter/packages/flutter/lib/src/widgets/overlay.dart').
OverlayState overlay(BuildContext context) => Overlay.of(context);`
请问有解决方案么？还是回退找个固定版本？

**Comment by xdd666t** [comment]
- 参考上面回复回退下述版本, 建议升级flutter sdk, 后续新版本不会做类似的兼容, 这样会使得使用flutter sdk最新版本的人大范围警告

```
dependencies:
  flutter_smart_dialog: ^4.8.2+3
```
