### ISSUE TITLE
Toast is opened with a delay

### ISSUE THREAD

**Issue by arnold-parge** [fluttercandies/flutter_smart_dialog#28]
**Steps to reproduce**
1. Open the toast with the time parameter of 5 seconds
2. Close the toast using `SmartDialog.dismiss(status: SmartStatus.toast);` within 1 second
3. Open the same toast again

**Actual Result**: The toast will wait for 4 seconds to open up again
**Expected Result**: The toast should open up immediately.

**Comment by xdd666t** [comment]
- Hi, the reason for this problem is because the original design toast concept conflicted, I made some attempts to solve this problem
- Please upgrade to the next version

```dart
dependencies:
  flutter_smart_dialog: ^3.4.0+1
```

- This is some of my test code, the effect is as expected

```dart
SmartDialog.showToast('test toast', time: Duration(seconds: 5));
await Future.delayed(Duration(seconds: 2));
await SmartDialog.dismiss(status: SmartStatus.toast);
SmartDialog.showToast('test toast', time: Duration(seconds: 5));
```

But I can't guarantee that in some special cases, the expected effect can still be achieved; if there is any problem, I hope to give me a feedback in time

Thanks!

**Comment by xdd666t** [comment]
The new version can solve this problem. If there is any problem, please mention it again.
